### ISSUE TITLE
Getting net::ERR_INCOMPLETE_CHUNKED_ENCODING error on a client

### ISSUE THREAD

**Issue by mrded** [antage/eventsource#22]
Hello,
During streaming on a client side, I'm continuously getting an error, which drops connection with a server. 

    GET /stream net::ERR_INCOMPLETE_CHUNKED_ENCODING

Can you please advice, what could be a problem? 
Thanks.

**Comment by antage** [comment]
Do you use any reverse proxy or caching proxy? Nginx?

**Comment by mrded** [comment]
Yes, we are using [cloudflare](https://www.cloudflare.com) with disabled caching, just for SSL purpose. 
With following settings https://monosnap.com/file/ETqkFoUQPlnS1Uo1wG8RfwEUl2GYYx

**Comment by antage** [comment]
I don't think you be able to use SSE via CloudFlare. Nginx requires `proxy_buffering off` for SSE but CloudFlare hasn't similar option.

**Comment by mrded** [comment]
I think it's a problem. Thank you!
